name: exam_2
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  dart_code_metrics: ^5.7.5
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.0.2
  font_awesome_flutter: ^10.4.0
  image_card: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
